stages:
  # - make_assets
  - embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

make_assets:
  plugin: command
  options:
    command: make
    locations:
      - chapters/template-chapter/template-topic/slides
    args:
      - all

embed_reveal:
  plugin: reveal_embed
  options:
    target: docusaurus
    extension: mdx
    build:
      template-chapter-template-topic: template-chapter-template-topic

docusaurus:
  plugin: docusaurus
  options:
    course_name: Hardware Software Interface
    math: true
    sidebar: js
    structure:
      - Introduction: chapters/landing-page/README.md
      - Lab 1 - Number Representation:
          - Binary and Hexadecimal:
              path: chapters/intro-computer-architecture/binary-hex/
              extra:
                - media/
              subsections:
                - Reading/: reading/
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Conversions/: conversions/
                            - Rotations/: rotations/
                            - Binary Even and Hexadecimal Odd/: odd-even/
          - Pointers in C:
              path: chapters/memory-layout/c-pointers/
              extra:
                - media/
              subsections:
                - Reading/: reading/
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Length and Equality with Bitwise Operations/: len-xor/
                            - Mirror/: mirror/
    # static_assets:
    #   - template-chapter-template-topic: /build/make_assets/chapters/template-chapter/template-topic/slides/_site
    config_meta:
      title: Hardware Software Interface
      url: http://localhost/
      baseUrl: /hardware-software-interface/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    config_socials:
      Main site: https://curs.upb.ro
      OCW: https://ocw.cs.pub.ro/courses/pclp2
      Facebook: https://www.facebook.com/10c1a
    copyright_string: OpenEdu Team
